# Generated by Django 5.0.4 on 2024-04-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProducto', models.CharField(max_length=100)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField()),
                ('TiempoCreacion', models.TimeField()),
            ],
        ),
    ]
