# Generated by Django 5.0.4 on 2024-04-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='FechaCreacion',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
